Repository fluencelabs/compute-marketplace, pull requests merged in 2024-04, with the labels that each got.

#399 fix: subgraph after offer updated [chain 442]
  subgraph/schema.graphql
  subgraph/src/mappings/capacity.ts
  subgraph/src/mappings/core.ts
  subgraph/src/mappings/deal-factory.ts
  subgraph/src/mappings/deal.ts
  subgraph/src/mappings/market.ts
  subgraph/src/mappings/utils.ts
  subgraph/src/models.ts
  subgraph/subgraph.yaml
  ts-client/src/dealCliClient/dealCliClient.ts
  ts-client/src/dealCliClient/indexerClient/generated.types.ts
  ts-client/src/dealCliClient/indexerClient/queries/offers-query.generated.ts
  ts-client/src/dealCliClient/indexerClient/queries/offers-query.graphql
  ts-client/src/dealCliClient/serializers/schemes.ts
  ts-client/src/dealCliClient/types/schemes.ts
  ts-client/src/dealExplorerClient/indexerClient/generated.types.ts
  ts-client/src/dealExplorerClient/indexerClient/queries/capacity-commitments-query.generated.ts
  ts-client/src/dealExplorerClient/indexerClient/queries/capacity-commitments-query.graphql
  ts-client/src/dealExplorerClient/indexerClient/queries/deals-query.generated.ts
  ts-client/src/dealExplorerClient/indexerClient/queries/deals-query.graphql
  ts-client/src/dealExplorerClient/indexerClient/queries/offers-query.generated.ts
  ts-client/src/dealExplorerClient/indexerClient/queries/offers-query.graphql
  ts-client/src/dealExplorerClient/indexerClient/queries/peers-query.generated.ts
  ts-client/src/dealExplorerClient/indexerClient/queries/peers-query.graphql
  ts-client/src/dealExplorerClient/indexerClient/queries/providers-query.generated.ts
  ts-client/src/dealExplorerClient/indexerClient/queries/providers-query.graphql
  ts-client/src/dealExplorerClient/serializers/filters.ts
  ts-client/src/dealExplorerClient/serializers/logics.ts
  ts-client/src/dealExplorerClient/serializers/orderby.ts
  ts-client/src/dealExplorerClient/serializers/schemes.ts
  ts-client/src/dealMatcherClient/dealMatcherClient.ts
  ts-client/src/dealMatcherClient/indexerClient/generated.types.ts
  ts-client/src/utils/indexerClient/serializers.ts
  ts-client/src/utils/rpcClientABC.ts
Labels: autorelease: pending, e2e

#405 refactor: Light refactoring
  .gitignore
  Makefile
  foundry.toml
  script/utils/String.sol
  src/core/CapacityConst.sol
  src/core/Core.sol
  src/core/GlobalConst.sol
  src/core/interfaces/ICapacityConst.sol
  src/core/interfaces/ICore.sol
  src/core/interfaces/IGlobalConst.sol
  src/core/modules/BaseModule.sol
  src/core/modules/capacity/Capacity.sol
  src/core/modules/capacity/Snapshot.sol
  src/core/modules/capacity/interfaces/ICapacity.sol
  src/core/modules/interfaces/IBaseModule.sol
  src/core/modules/market/DealFactory.sol
  src/core/modules/market/Market.sol
  src/core/modules/market/Matcher.sol
  src/core/modules/market/Offer.sol
  src/core/modules/market/interfaces/IDealFactory.sol
  src/core/modules/market/interfaces/IMatcher.sol
  src/core/modules/market/interfaces/IOffer.sol
  src/deal/Config.sol
  src/deal/Deal.sol
  src/deal/DealSnapshot.sol
  src/deal/WorkerManager.sol
  src/deal/interfaces/IConfig.sol
  src/deal/interfaces/IDeal.sol
  src/dev/OwnableFaucet.sol
  src/dev/test/CapacityConstWithPublicInternals.sol
  src/dev/test/ConfigWithPublicInternals.sol
  src/dev/test/DealWithPublicInternals.sol
  src/dev/test/interfaces/ICapacityConstWithPublicInternals.sol
  src/dev/test/interfaces/IConfigWithPublicInternals.sol
  src/dev/test/interfaces/IDealWithPublicInternals.sol
  src/mocks/RandomXProxyMock.sol
  src/utils/Common.sol
  src/utils/Whitelist.sol
  test/OwnableFaucet.t.sol
  test/core/CapacityConst.t.sol
  test/core/Core.t.sol
  test/core/capacity/CapacityCommitment.t.sol
  test/core/capacity/Vesting.t.sol
  test/core/market/DealFactory.t.sol
  test/core/market/Market.t.sol
  test/core/market/Matcher.t.sol
  test/core/market/Offer.t.sol
  test/deal/AddComputeUnits.t.sol
  test/deal/AddWorkers.t.sol
  test/deal/CommitPeriod.t.sol
  test/deal/ConfigContract.t.sol
  test/deal/GetStatus.t.sol
  test/deal/Rewards.t.sol
  test/utils/DealHelper.sol
  test/utils/TestHelper.sol
  test/utils/TestWithDeployment.sol
Labels: e2e

#397 feat!: oracle role CHAIN-444
  deployments/local.json
  integration-tests/package-lock.json
  src/core/CapacityConst.sol
  src/core/interfaces/ICapacityConst.sol
  test/core/CapacityConst.t.sol
  test/core/Core.t.sol
  test/utils/TestWithDeployment.sol
Labels: e2e

#406 fix: remove invalid release logic from submit proof
  deployments/local.json
  src/core/modules/capacity/Capacity.sol
Labels: e2e

#414 feat: optimise query for cc detail view [CHAIN-452]
  ts-client/src/dealExplorerClient/indexerClient/generated.types.ts
  ts-client/src/dealExplorerClient/indexerClient/queries/capacity-commitments-query.generated.ts
  ts-client/src/dealExplorerClient/indexerClient/queries/capacity-commitments-query.graphql
Labels: e2e

#421 fix: negative-active-workers-CHAIN-456
  subgraph/src/mappings/deal.ts
Labels: e2e

#402 feat: prettier for whole monorepo [feat CHAIN-446]
  .editorconfig
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .prettierignore
  .prettierrc
  Makefile
  README.md
  docker/docker-compose.yml
  integration-tests/README.md
  integration-tests/package-lock.json
  integration-tests/tsconfig.json
  slither.config.json
  subgraph/.prettierignore
  subgraph/README.md
  subgraph/configs/dar-networks-config.json
  subgraph/configs/kras-networks-config.json
  subgraph/configs/local-networks-config.json
  subgraph/configs/stage-networks-config.json
  subgraph/package.json
  subgraph/schema.graphql
  subgraph/scripts/import-config-networks.ts
  ts-client/.prettierignore
  ts-client/README.md
  ts-client/codegen-deal-cli-indexer.ts
  ts-client/codegen-deal-explorer-indexer.ts
  ts-client/codegen-deal-matcher-indexer.ts
  ts-client/replace-imports.js
  ts-client/src/dealMatcherClient/dealMatcherClient.ts
  ts-client/tests/integration/constants.ts
  ts-client/tests/integration/fixture.ts
  ts-client/tests/integration/scripts/create-pure-market.test.ts
  ts-client/tests/unittests/dealMatcherClient.test.ts
  ts-client/tests/unittests/indexerClientABC.test.ts
  ts-client/yarn.lock
Labels: e2e

#424 feat: add subgraph versioning v2
  Makefile
  subgraph/README.md
  subgraph/deployments/dar.txt
  subgraph/deployments/kras.txt
  subgraph/deployments/stage.txt
  subgraph/fluence-graph.sh
  subgraph/package.json
  ts-client/src/utils/indexerClient/config.ts
  ts-client/tests/unittests/indexerClientABC.test.ts
Labels: autorelease: pending, e2e

#430 feat: deploy subgraph to dar and kras
  subgraph/deployments/dar.txt
  subgraph/deployments/kras.txt
  subgraph/subgraph.yaml
  ts-client/src/utils/indexerClient/config.ts
Labels: e2e

#426 feat: storage checker
  .github/workflows/storage-dump.yml
  .github/workflows/test.yml
  foundry.toml
  src/mocks/StorageMocks.sol
  storage-checker/compare-slots.js
  storage-checker/compare.js
  storage-checker/storage-layout-dump.json
  storage-checker/store-layout.js
Labels: e2e, review-storage-layout-change

#432 feat: new-column [CHAIN-483]
  ts-client/src/dealExplorerClient/indexerClient/generated.types.ts
  ts-client/src/dealExplorerClient/indexerClient/queries/providers-query.generated.ts
  ts-client/src/dealExplorerClient/indexerClient/queries/providers-query.graphql
  ts-client/src/dealExplorerClient/serializers/schemes.ts
  ts-client/src/dealExplorerClient/types/schemes.ts
Labels: e2e, review-storage-layout-change
